# Generated by Django 6.0.5 on 2026-05-14 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('middle_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('phone_number', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:\\+2547|\\+2541|07|01)\\d{8}$')])),
                ('status', models.CharField(choices=[('Active', 'active'), ('Suspended', 'suspended'), ('Work Leave', 'work leave')], default=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('middle_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('phone_number', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:\\+2547|\\+2541|07|01)\\d{8}$')])),
                ('status', models.CharField(choices=[('Active', 'active'), ('Suspended', 'suspended'), ('Work Leave', 'work leave')], default=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('middle_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('phone_number', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:\\+2547|\\+2541|07|01)\\d{8}$')])),
                ('number_of_cows', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'active'), ('Suspended', 'suspended'), ('Pregnancy Leave', 'pregnancy leave')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_or_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.route')),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('middle_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]$')])),
                ('phone_number', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:\\+2547|\\+2541|07|01)\\d{8}$')])),
                ('status', models.CharField(choices=[('Active', 'active'), ('Suspended', 'suspended'), ('Work Leave', 'work leave')], default=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.route')),
            ],
        ),
    ]
