# Generated by Django 6.0.5 on 2026-05-16 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('middle_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:\\+2547|\\+2541|07|01)\\d{8}$')])),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Suspend', 'suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatedd_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('clerk', 'Clerk'), ('collector', 'Collector'), ('farmer', 'Farmer')], max_length=20)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('middle_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:\\+2547|\\+2541|07|01)\\d{8}$')])),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Suspend', 'suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatedd_at', models.DateTimeField(auto_now=True)),
                ('number_of_cows', models.IntegerField()),
                ('route_or_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('middle_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Farmer's name can only be in letters", regex='^[a-zA-Z]+$')])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:\\+2547|\\+2541|07|01)\\d{8}$')])),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Suspend', 'suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatedd_at', models.DateTimeField(auto_now=True)),
                ('collection_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.route')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
