# Generated by Django 6.0.5 on 2026-05-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerk',
            old_name='updatedd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='collector',
            old_name='updatedd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='updatedd_at',
            new_name='updated_at',
        ),
    ]
