# Generated by Django 6.0.5 on 2026-05-16 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name can only be in letters', regex='^[a-zA-Z]$')])),
            ],
        ),
        migrations.CreateModel(
            name='FeedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name can only be in letters', regex='^[a-zA-Z]$')])),
            ],
        ),
        migrations.CreateModel(
            name='NetWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brandcategory')),
                ('feed_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.feedcategory')),
                ('net_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.netweight')),
            ],
            options={
                'unique_together': {('brand_category', 'feed_category', 'net_weight')},
            },
        ),
        migrations.CreateModel(
            name='FeedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.feedstock')),
            ],
        ),
    ]
